spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_bidding
    username: Ratana123
    password: Ratana123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: sanratana18@gmail.com
    password: cbep qoag nqsh sdmi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  freemarker:
    template-loader-path: classpath:/templates/
server:
  port: 8080

#Swagger
#http://localhost:8090/swagger-ui/index.html#/